GET http://127.0.0.1:8000/api/subject/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzI0MDM5LCJpYXQiOjE3NTE3MjM3MzksImp0aSI6ImM4YjkxODk1ZGM3MTQ0NWM5MTk0MGEwOTM2NWNjOTFiIiwidXNlcl9pZCI6MX0.pUduvmKByYPhcMhpJUlKaHZp1RE_jrwWIaHFuW2oQck

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username" : "Brent",
  "password" : "pogi"
}

###
POST http://127.0.0.1:8000/api/subject/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzI0MDM5LCJpYXQiOjE3NTE3MjM3MzksImp0aSI6ImM4YjkxODk1ZGM3MTQ0NWM5MTk0MGEwOTM2NWNjOTFiIiwidXNlcl9pZCI6MX0.pUduvmKByYPhcMhpJUlKaHZp1RE_jrwWIaHFuW2oQck
Content-Type: application/json

{
  "name" : "Science",
  "description" : "Science is a systematic endeavor that builds and organizes knowledge in the form of testable explanations and predictions about the universe.",
  "user": 1
}