# Generated by Django 5.2.3 on 2025-10-24 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(default='gemini-2.5-flash', max_length=100)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='tracker.notes')),
            ],
            options={
                'verbose_name_plural': 'Note Summaries',
            },
        ),
    ]
